### ISSUE TITLE
Incorrect PYRENODE_RUNTIME choices in Readme

### ISSUE THREAD

**Issue by serweryn617** [antmicro/pyrenode3#6]
README says that `PYRENODE_RUNTIME` parameter should be either `mono` or `dotnet`:

> PYRENODE_RUNTIME -- Specifies runtime which is used to run Renode. Supported runtimes: `mono` (default), `dotnet` (.NET).

This is incorrect, to select .NET Python expects the value to be `coreclr`, see:

https://github.com/antmicro/pyrenode3/blob/b62c795a29f620b53192134435b0f68a21a1924e/src/pyrenode3/__init__.py#L11C1-L12C64

```py
    if runtime not in ["mono", "coreclr"]:
        raise ImportError(f"Runtime {runtime!r} not supported")
```

Proposed fix: #5

**Comment by PiotrZierhoffer** [comment]
Closed with 7f9bddca
